package paul.dao;


import org.springframework.stereotype.Repository;
import paul.domain.Document;

import java.util.List;
import java.util.Map;
@Repository
public interface DocumentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbg.generated
     */
    //动态插入
    int insertSelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbg.generated
     */
    Document selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_inf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Document record);
    //动态查询总数量
    int selectCount(Document document);
    //分页动态查询
    List<Document> selectWithParam(Map map);
}