package paul.dao;

import org.springframework.stereotype.Repository;
import paul.domain.Job;

import java.util.List;
import java.util.Map;
@Repository
public interface JobDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbg.generated
     */
    int insert(Job record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbg.generated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_inf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Job record);
    //查出所有的工作
    List<Job> selectAllJob();
    //动态更新
    int updateByPrimaryKeySelective(Job record);

    //动态插入
    int insertSelective(Job record);

    //查工作
    Job selectByPrimaryKey(Integer id);
    //动态查询数量
    int selectCount(Job job);
    //分页动态查询
    List<Job> selectWithParam(Map map);
}