package paul.dao;


import org.springframework.stereotype.Repository;
import paul.domain.Notice;
import java.util.List;
import java.util.Map;
@Repository
public interface NoticeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_inf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notice record);
    //分页动态查询
    List<Notice> selectWithParam(Map<String, Object> map);
    //动态更新
    int updateNotice(Notice record);
    //动态查询总数量
    int selectCount(Notice notice);
    //动态插入
    int insertSelective(Notice record);

}