package paul.domain;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.dept_id
     *
     * @mbg.generated
     */
    private Department department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.job_id
     *
     * @mbg.generated
     */
    private Job job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.card_code
     *
     * @mbg.generated
     */
    private Integer card_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.post_code
     *
     * @mbg.generated
     */
    private String post_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.qq_code
     *
     * @mbg.generated
     */
    private Integer qq_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.party
     *
     * @mbg.generated
     */
    private String party;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_inf.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.id
     *
     * @return the value of employee_inf.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.id
     *
     * @param id the value for employee_inf.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Job getJob() {
        return job;
    }

    public void setJob(Job job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.name
     *
     * @return the value of employee_inf.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.name
     *
     * @param name the value for employee_inf.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.card_code
     *
     * @return the value of employee_inf.card_code
     *
     * @mbg.generated
     */
    public Integer getCard_code() {
        return card_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.card_code
     *
     * @param card_code the value for employee_inf.card_code
     *
     * @mbg.generated
     */
    public void setCard_code(Integer card_code) {
        this.card_code = card_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.address
     *
     * @return the value of employee_inf.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.address
     *
     * @param address the value for employee_inf.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.post_code
     *
     * @return the value of employee_inf.post_code
     *
     * @mbg.generated
     */
    public String getPost_code() {
        return post_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.post_code
     *
     * @param post_code the value for employee_inf.post_code
     *
     * @mbg.generated
     */
    public void setPost_code(String post_code) {
        this.post_code = post_code == null ? null : post_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.phone
     *
     * @return the value of employee_inf.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.phone
     *
     * @param phone the value for employee_inf.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.qq_code
     *
     * @return the value of employee_inf.qq_code
     *
     * @mbg.generated
     */
    public Integer getQq_code() {
        return qq_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.qq_code
     *
     * @param qq_code the value for employee_inf.qq_code
     *
     * @mbg.generated
     */
    public void setQq_code(Integer qq_code) {
        this.qq_code = qq_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.email
     *
     * @return the value of employee_inf.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.email
     *
     * @param email the value for employee_inf.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.sex
     *
     * @return the value of employee_inf.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.sex
     *
     * @param sex the value for employee_inf.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.party
     *
     * @return the value of employee_inf.party
     *
     * @mbg.generated
     */
    public String getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.party
     *
     * @param party the value for employee_inf.party
     *
     * @mbg.generated
     */
    public void setParty(String party) {
        this.party = party == null ? null : party.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_inf.create_date
     *
     * @return the value of employee_inf.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_inf.create_date
     *
     * @param create_date the value for employee_inf.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }
}