package paul.domain;

import com.sun.istack.internal.NotNull;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.id
     *
     * @mbg.generated
     */
    private Integer id;
    private String name;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.username
     *
     * @mbg.generated
     */
    private String username;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.password
     *
     * @mbg.generated
     */
    private String password;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.status
     *
     * @mbg.generated
     */
    private String status;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.createDate
     *
     * @mbg.generated
     */
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private Date createDate;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.role
     *
     * @mbg.generated
     */
    private String role;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.id
     *
     * @return the value of user_inf.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.id
     *
     * @param id the value for user_inf.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.username
     *
     * @return the value of user_inf.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.username
     *
     * @param username the value for user_inf.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.password
     *
     * @return the value of user_inf.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.password
     *
     * @param password the value for user_inf.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.status
     *
     * @return the value of user_inf.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.status
     *
     * @param status the value for user_inf.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.createDate
     *
     * @return the value of user_inf.createDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.createDate
     *
     * @param createDate the value for user_inf.createDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.role
     *
     * @return the value of user_inf.role
     *
     * @mbg.generated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.role
     *
     * @param role the value for user_inf.role
     *
     * @mbg.generated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}